name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        # .env placeholder
        envkey_APP_DEBUG: 1
        envkey_APP_DISPLAY_ERROR_DETAILS: 1
        envkey_DB_DSN: ""
        envkey_DB_USER: ""
        envkey_DB_PASS: ""
      
        directory: ./
        file_name: .env

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Setup node
      uses: actions/setup-node@v1
      
    - name: Install npm dependencies
      run: npm install
      
    - name: Npm Build
      run: npm run build

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
